authorName: default
experimentName: example_cifar10-network-morphism-test
trialConcurrency: 1
maxExecDuration: 72h
maxTrialNum: 6000
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 224
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 1000
trial:
  command: CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 srun -N 1 -n 1 --ntasks-per-node=1 --cpus-per-task=24 python3 cifar10_keras_multigpu_ps.py
  codeDir: .
  gpuNum: 0
