authorName: default
experimentName: example_imagenet-network-morphism-test
trialConcurrency: 1
maxExecDuration: 12h
maxTrialNum: 6000
#choice: local, remote, pai
trainingServicePlatform: local
#searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, NetworkMorphism
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: NetworkMorphism
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    #for now, this tuner only supports cv domain
    task: cv
    #input image width
    input_width: 224
    #input image channel
    input_channel: 3
    #number of classes
    n_output_node: 1000
trial:
    command: NPU_NUM=8 \
             srun -N 1 -n 1 --ntasks-per-node=1 --cpus-per-task=191 \
             python3 imagenet_train.py \
             --slave 1 \
             --ip 172.17.0.2 \
             --batch_size 256 \
             --train_data_dir /home/data/train/ \
             --val_data_dir /home/data/val/ \
             --warmup_1 60 \   
             --warmup_2 70 \   
             --warmup_3 80  
             
    codeDir: .
    gpuNum: 0
